name: pfa
description: Mini Quiz - Application de quiz sur le dÃ©veloppement
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.0

  # UI et utilitaires
  provider: ^6.1.1
  intl: ^0.19.0

  # Animations
  lottie: ^2.7.0

  # Pour le partage
  share_plus: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true



